# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wintit
description: Le seul logiciel professionnel abordable de gestion de portefeuilles titres
baseurl: "/wintit" # the subpath of your site, e.g. /blog
url: "http://wintit.fr" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

#docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll   -it -p 127.0.0.1:4000:4000 jekyll/jekyll